build:
  image: dockerepo/glide
  commands:
    - glide install
    - go build
    - go test
  bundle:
    when:
      branch: master
  clone:
    path: github.com/xwjdsh/droneTest
  cache:
    mount:
      - vendor
      - .git
publish:
  docker:
    registry: registry.sunwen.in
    username: $$USERNAME
    password: $$PASSWORD
    email: iwendellsun@gmail.com
    repo: wendell/droneTest
    tag: 
      - latest
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest
    cache:
      mount:
        - docker/image.tar
