build:
  image: dockerepo/glide
  commands:
    - glide install
    - CGO_ENABLED=0 go build -a -installsuffix cgo
    - go test
  bundle:
    when:
      branch: master
  clone:
    path: github.com/xwjdsh/droneTest
  cache:
    mount:
      - vendor
      - .git

publish:
  docker:
    registry: registry.sunwen.in
    username: $$USERNAME
    password: $$PASSWORD
    email: iwendellsun@gmail.com
    repo: wendell/drone-test
    tag: 
      - $$BRANCH-$$COMMIT
      - latest
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest
    cache:
      mount:
        - docker/image.tar

deploy:
  ssh:
    host: $$SSH_HOST
    user: $$SSH_USER
    port: $$SSH_PORT
    commands:
      - cd ~/deploy;./drone-test.sh
